export const ACTIONS_QUESTION_SEARCH = 'ACTIONS_QUESTION_SEARCH';
export const ACTIONS_ANSWER_SEARCH = 'ACTIONS_ANSWER_SEARCH';
export const ACTIONS_QUESTION_AUTHOR = 'ACTIONS_QUESTION_AUTHOR';
export const ACTIONS_QUESTION_TAG = 'ACTIONS_QUESTION_TAG';
